### ISSUE TITLE
passing props to nested components? 

### ISSUE THREAD

**Issue by ytbryan** [e-e-e/vue-pass-props#1] opened 2018-07-14 16:41 UTC
Thank you for this plugin. 

How do you pass the props down to nested components in the slots? 

Considering this example: 

formfor.vue
```javascript
  <form :attr="model" :action="computePath" accept-charset="UTF-8" method="post"> 
    <input name="utf8" type="hidden" value="✓">
    <input v-if="isPatch" type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" :value="authenticity_token">
   <pass-props :attr="model"><slot/></pass-props>
  </form>
```

at the index.html, 

A working copy is: 
```html
<form-for model="something">
   <text-field></text-field>
</form-for>
```

> In this case, text-field received the `model` and pass it as `:attr`

A non-working example happens when nesting occurs

```html
<form-for model="something">
   <div class="field>
      <text-field></text-field>
   </div>
</form-for>
```

In this example, the `div class=field` prevents the props from passing down. 

Do you know why? And how can i fix it?

**Comment by e-e-e** [comment] 2018-07-15 09:27
The problem is that it does not recursively pass the values down to nested components. In your case that is not working, it is because the props are being assigned to the div element. This is expected behaviour and I am not sure if its worth the effort to accommodate your case. 

Instead, perhaps its better to use the Provide/Inject mechanism - https://vuejs.org/v2/api/#provide-inject. Or restructure your code so that the div is a field component which in turn passes the required props to the text-field.

**Closed as completed by e-e-e** 2018-07-15 09:27 UTC

**Comment by ytbryan** [comment] 2018-07-15 11:22
Thanks @e-e-e. It's exactly what i'm looking for. Thanks for the pointer !

**Comment by e-e-e** [comment] 2018-07-15 11:38
No problem at all @ytbryan. Happy to have helped.
